config/routes.rb
Rails.application.routes.draw do
  # resources :customers, only: %i[index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "customers#index"
  # get "/customers", to: "customers#index", as: "customers" # companies_path
  # get "/customers/alphabetized", to: "customers#alphabetized", as: "acustomers" # companies_path
  # get "/companies/:id", to: "companies#show", as: "company" # company_path
  resources :customers do
    collection do
      get "alphabetized"
      get "missing_email"
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ""])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <p class="title is-5">  <%= customer.full_name %></p>
      <% if customer.image.present? %>
      <%= image_tag customer.image.variant(resize_to_limit: [280, 280]).processed  %>
          <% end %>
         <br><br><%= customer.phone_number %>
         <br> <br><%= customer.email_address %>
         <% if customer.notes.present? %>
          <br><br><strong>Notes: </strong><%= customer.notes %>
          <% end %>
      </div>

  </div>


</div>

app/views/customers/alphabetized.html.erb
<h3 class="title is-3 m-5">All Customers - Alphabetized </h3>
<p><%= link_to "Customers - Home", root_path %></p>
<p><%= link_to "Customers - no email", missing_email_customers_path %></p>

<div class="columns is-multiline">
 <%= render @customers %>
 </div>

app/views/customers/index.html.erb
<h3 class="title is-3 m-5">All Customers </h3>
<p><%= link_to "Customers - Alphabetized", alphabetized_customers_path %></p>
<p><%= link_to "Customers - no email", missing_email_customers_path %></p>

<div class="columns is-multiline">
 <%= render @customers %>
 </div>

app/views/customers/missing_email.html.erb
<h3 class="title is-3 m-5">All Customers with missing email </h3>
<p><%= link_to "Customers - Home", root_path %></p>
<p><%= link_to "Customers - Alphabetized", alphabetized_customers_path %></p>

<div class="columns is-multiline">
 <%= render @customers %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerRelationManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>